---
- hosts: server
  become: true
  remote_user: root
  become_method: sudo
  tasks:
    - name: Install java
      shell: apt-get install default-jdk -y
      
    - name: Download Tomcat
      get_url: url=https://archive.apache.org/dist/tomcat/tomcat-8/v8.0.27/bin/apache-tomcat-8.0.27.tar.gz dest=/home/ubuntu

    - name: Extract archive
      unarchive: src=/home/ubuntu/apache-tomcat-8.0.27.tar.gz dest=/home/ubuntu remote_src=yes
      
    - name: Download Application
      get_url: url=http://34.219.81.207:8081/artifactory/Prod/CounterWebApp.war dest=/home/ubuntu
      
    - name: Copy application
      shell: cp /home/ubuntu/CounterWebApp.war /home/ubuntu/apache-tomcat-8.0.27/webapps/
      
    - name: stop apache-tomcat-8.0.27
      shell: /home/ubuntu/apache-tomcat-8.0.27/bin/shutdown.sh
     
    - name: start apache-tomcat-8.0.27
      shell: /home/ubuntu/apache-tomcat-8.0.27/bin/startup.sh

